name: lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Falco on valid VCL with high verbosity
        uses: ain/falco-github-action@v1
        with:
          subcommand: lint
          options: "-vv"
          target: cdn/terraform/vcl/*.vcl

  fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Lint VCL
        uses: ain/falco-github-action@v1
        with:
          subcommand: fmt
          options: "-w"
          target: cdn/terraform/vcl/*.vcl
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action #mandatory for the output to show up in ${{ steps }}
        with:
          commit_message: Apply falco fmt changes